name: red_carga
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  url_launcher: ^6.2.2
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  file_picker: ^8.1.2
  path_provider: ^2.1.1
  camera: ^0.11.0+2
  pdf: ^3.11.1
  share_plus: ^10.1.2
  google_maps_flutter: ^2.14.0
  location: ^8.0.1
  geolocator: ^14.0.2
  stomp_dart_client: ^3.0.1
  stream_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Assets (im√°genes, iconos, etc.)
  assets:
    - assets/images/
    - assets/icons/
    - lib/features/deals/assets_temp/
